train_data = [
    {"text": "turn on the light", "label": "turn_on_light"},
    {"text": "could you please turn off the light", "label": "turn_off_light"},
    {"text": "can you turn on the fan", "label": "turn_on_fan"},
    {"text": "please turn off the fan", "label": "turn_off_fan"},
    {"text": "turn on the air conditioner", "label": "turn_on_air_conditional"},
    {"text": "could you turn off the air conditioner", "label": "turn_off_air_conditional"},
    {"text": "switch on the lights", "label": "turn_on_light"},
    {"text": "switch off the lights", "label": "turn_off_light"},
    {"text": "It's a bit bright", "label": "turn_off_light"},
    {"text": "It's bright", "label": "turn_off_light"},
    {"text": "It's too bright", "label": "turn_off_light"},
    {"text": "activate the fan", "label": "turn_on_fan"},
    {"text": "deactivate the fan", "label": "turn_off_fan"},
    {"text": "start the air conditioner", "label": "turn_on_air_conditional"},
    {"text": "stop the air conditioner", "label": "turn_off_air_conditional"},
    {"text": "can you play some music", "label": "others"},
    {"text": "what's the weather like today?", "label": "others"},
    {"text": "tell me a joke", "label": "others"},
    {"text": "how are you doing?", "label": "others"},
    {"text": "who won the game last night?", "label": "others"},
    {"text": "increase the volume", "label": "others"},
    {"text": "dim the lights to 50%", "label": "turn_on_light"},
    {"text": "what time is it?", "label": "others"},
    {"text": "open the garage door", "label": "others"},
    {"text": "close the blinds", "label": "others"},
    {"text": "set an alarm for 7 am", "label": "others"},
    {"text": "good morning", "label": "others"},
    {"text": "what's your name?", "label": "others"},
    {"text": "lock the front door", "label": "others"},
    {"text": "unlock the back door", "label": "others"},
    {"text": "make me a coffee", "label": "others"},
    {"text": "what's the news today?", "label": "others"},
    {"text": "can you please turn on the lights", "label": "turn_on_light"},
    {"text": "would you mind turning off the lights", "label": "turn_off_light"},
    {"text": "please turn on the fan", "label": "turn_on_fan"},
    {"text": "can you deactivate the fan", "label": "turn_off_fan"},
    {"text": "turn the air conditioner on", "label": "turn_on_air_conditional"},
    {"text": "turn the air conditioner off", "label": "turn_off_air_conditional"},
    {"text": "I'm a bit hot", "label": "turn_on_fan"},
    {"text": "It's getting warm in here", "label": "turn_on_fan"},
    {"text": "It's too dark to see", "label": "turn_on_light"},
    {"text": "I can't see anything", "label": "turn_on_light"},
    {"text": "It's too bright in here", "label": "turn_off_light"},
    {"text": "I'm cold", "label": "turn_on_air_conditional"},
    {"text": "It's too chilly", "label": "turn_off_air_conditional"},
    {"text": "please start the fan", "label": "turn_on_fan"},
    {"text": "can you turn the fan off", "label": "turn_off_fan"},
    {"text": "switch on the air conditioner", "label": "turn_on_air_conditional"},
    {"text": "could you switch off the air conditioner", "label": "turn_off_air_conditional"},
    {"text": "activate the lights", "label": "turn_on_light"},
    {"text": "deactivate the lights", "label": "turn_off_light"},
    {"text": "it's a bit too dark", "label": "turn_on_light"},
    {"text": "it's a bit chilly", "label": "turn_on_air_conditional"},
    {"text": "it's too hot in here", "label": "turn_on_fan"},
    {"text": "reduce the brightness", "label": "turn_off_light"},
    {"text": "increase the brightness", "label": "turn_on_light"},
    {"text": "make it cooler", "label": "turn_on_air_conditional"},
    {"text": "make it warmer", "label": "turn_off_air_conditional"},
    {"text": "could you lower the lights?", "label": "turn_off_light"},
    {"text": "can you dim the lights?", "label": "turn_off_light"},
    {"text": "can you brighten the room?", "label": "turn_on_light"},
    {"text": "it's very bright here", "label": "turn_off_light"},
    {"text": "it's very dark here", "label": "turn_on_light"},
    {"text": "can you make it brighter?", "label": "turn_on_light"},
    {"text": "can you turn down the lights?", "label": "turn_off_light"},
    {"text": "it's a bit warm", "label": "turn_on_fan"},
    {"text": "it's very warm", "label": "turn_on_fan"},
    {"text": "it's quite warm", "label": "turn_on_fan"},
    {"text": "it's a bit cold", "label": "turn_on_air_conditional"},
    {"text": "it's very cold", "label": "turn_on_air_conditional"},
    {"text": "it's quite cold", "label": "turn_on_air_conditional"},
    {"text": "start the AC", "label": "turn_on_air_conditional"},
    {"text": "stop the AC", "label": "turn_off_air_conditional"},
    {"text": "it's too dark to read", "label": "turn_on_light"},
    {"text": "can you make it cooler in here?", "label": "turn_on_air_conditional"},
    {"text": "can you make it warmer in here?", "label": "turn_off_air_conditional"},
    {"text": "it's too hot", "label": "turn_on_fan"},
    {"text": "it's too cold", "label": "turn_on_air_conditional"},
    {"text": "can you turn the light on", "label": "turn_on_light"},
    {"text": "would you turn off the light for me", "label": "turn_off_light"},
    {"text": "please turn the fan on", "label": "turn_on_fan"},
    {"text": "could you switch off the fan", "label": "turn_off_fan"},
    {"text": "I need the air conditioner on", "label": "turn_on_air_conditional"},
    {"text": "can you stop the air conditioner", "label": "turn_off_air_conditional"},
    {"text": "can you switch on the lights", "label": "turn_on_light"},
    {"text": "please switch off the lights", "label": "turn_off_light"},
    {"text": "can you activate the fan", "label": "turn_on_fan"},
    {"text": "can you deactivate the fan", "label": "turn_off_fan"},
    {"text": "I feel warm, can you start the air conditioner", "label": "turn_on_air_conditional"},
    {"text": "stop the AC", "label": "turn_off_air_conditional"},
    {"text": "play the next song", "label": "others"},
    {"text": "how's the weather today?", "label": "others"},
    {"text": "tell me a funny story", "label": "others"},
    {"text": "what time do we have?", "label": "others"},
    {"text": "open the window", "label": "others"},
    {"text": "Can you turn off the AC", "label": "turn_off_air_conditional"},
    {"text": "Can you turn off the air conditional", "label": "turn_off_air_conditional"},
    {"text": "I'm hungry", "label": "others"},
    {"text": "I don't know", "label": "others"},
    {"text": "I'm bored", "label": "others"},
    {"text": "I'm sleepy", "label": "others"},
    {"text": "I'm lost", "label": "others"},
    {"text": "I'm curious", "label": "others"},
    {"text": "I'm tired", "label": "others"},
    {"text": "I'm unsure", "label": "others"},
    {"text": "I'm excited", "label": "others"},
    {"text": "I'm stressed", "label": "others"},
    {"text": "I'm confused", "label": "others"},
    {"text": "I'm relaxed", "label": "others"},
    {"text": "I'm disappointed", "label": "others"},
    {"text": "I'm surprised", "label": "others"},
    {"text": "I'm nervous", "label": "others"},
    {"text": "I'm scared", "label": "others"},
    {"text": "I'm hopeful", "label": "others"},
    {"text": "I'm frustrated", "label": "others"},
    {"text": "I'm content", "label": "others"},
    {"text": "I'm amazed", "label": "others"},
    {"text": "I'm feeling tired today", "label": "others"},
    {"text": "I don't know what to do", "label": "others"},
    {"text": "I'm hungry, what should I eat?", "label": "others"},
    {"text": "I'm feeling happy today", "label": "others"},
    {"text": "I need some advice", "label": "others"},
    {"text": "Can you recommend a good book?", "label": "others"},
    {"text": "What's your favorite color?", "label": "others"},
    {"text": "Tell me something interesting", "label": "others"},
    {"text": "Can you help me with my homework?", "label": "others"},
    {"text": "What should I wear today?", "label": "others"},
    {"text": "I'm bored, what can I do?", "label": "others"},
    {"text": "Can you suggest a movie?", "label": "others"},
    {"text": "Do you think it will rain tomorrow?", "label": "others"},
    {"text": "How can I relax after a long day?", "label": "others"},
    {"text": "What are your hobbies?", "label": "others"},
    {"text": "Can you explain how computers work?", "label": "others"},
    {"text": "What's the meaning of life?", "label": "others"},
    {"text": "How do I make friends?", "label": "others"},
    {"text": "Can you tell me about history?", "label": "others"},
    {"text": "I'm feeling sad, can you cheer me up?", "label": "others"}
]


val_data = [
    {"text": "close the drapes", "label": "others"},
    {"text": "play another song", "label": "others"},
    {"text": "have a good night", "label": "others"},
    {"text": "who's the current president?", "label": "others"},
    {"text": "please turn off the alarm", "label": "others"},
    {"text": "lock the front windows", "label": "others"},
    {"text": "can you make some tea", "label": "others"},
    {"text": "tell me the latest news", "label": "others"},
    {"text": "could you turn on the lights for me", "label": "turn_on_light"},
    {"text": "would you mind turning off the lights", "label": "turn_off_light"},
    {"text": "could you please turn the fan on", "label": "turn_on_fan"},
    {"text": "please switch off the fan", "label": "turn_off_fan"},
    {"text": "I need to cool down, can you turn the AC on", "label": "turn_on_air_conditional"},
    {"text": "can you switch the AC off", "label": "turn_off_air_conditional"},
    {"text": "It's getting too hot here", "label": "turn_on_fan"},
    {"text": "The room is too warm", "label": "turn_on_fan"},
    {"text": "It's pitch dark in here", "label": "turn_on_light"},
    {"text": "I can't see clearly", "label": "turn_on_light"},
    {"text": "There's too much light", "label": "turn_off_light"},
    {"text": "I'm freezing", "label": "turn_on_air_conditional"},
    {"text": "It's way too cold", "label": "turn_off_air_conditional"},
    {"text": "please activate the lights", "label": "turn_on_light"},
    {"text": "please deactivate the lights", "label": "turn_off_light"},
    {"text": "turn on the lights please", "label": "turn_on_light"},
    {"text": "turn off the lights please", "label": "turn_off_light"},
    {"text": "could you turn the fan on", "label": "turn_on_fan"},
    {"text": "could you turn the fan off", "label": "turn_off_fan"},
    {"text": "switch on the AC", "label": "turn_on_air_conditional"},
    {"text": "switch off the AC", "label": "turn_off_air_conditional"},
    {"text": "I need the AC on", "label": "turn_on_air_conditional"},
    {"text": "I need the AC off", "label": "turn_off_air_conditional"},
    {"text": "can you activate the lights?", "label": "turn_on_light"},
    {"text": "can you deactivate the lights?", "label": "turn_off_light"},
    {"text": "it's a bit warm, can you turn on the fan?", "label": "turn_on_fan"},
    {"text": "it's too cold, can you turn on the air conditioner?", "label": "turn_on_air_conditional"},
    {"text": "it's too hot, can you turn on the fan?", "label": "turn_on_fan"},
    {"text": "can you make it less bright?", "label": "turn_off_light"},
    {"text": "can you make it more bright?", "label": "turn_on_light"},
    {"text": "can you make it less dark?", "label": "turn_on_light"},
    {"text": "can you make it cooler?", "label": "turn_on_air_conditional"},
    {"text": "can you make it warmer?", "label": "turn_off_air_conditional"},
    {"text": "it's a bit too cold", "label": "turn_on_air_conditional"},
    {"text": "it's a bit too warm", "label": "turn_on_fan"},
    {"text": "please make it cooler", "label": "turn_on_air_conditional"},
    {"text": "please make it warmer", "label": "turn_off_air_conditional"},
    {"text": "can you lower the brightness?", "label": "turn_off_light"},
    {"text": "can you increase the brightness?", "label": "turn_on_light"},
    {"text": "can you make the room cooler?", "label": "turn_on_air_conditional"},
    {"text": "can you make the room warmer?", "label": "turn_off_air_conditional"},
    {"text": "I need a vacation", "label": "others"},
    {"text": "What's the best way to save money?", "label": "others"},
    {"text": "Can you explain quantum physics?", "label": "others"},
    {"text": "I think I lost my keys", "label": "others"},
    {"text": "How do I cook spaghetti?", "label": "others"},
    {"text": "I'm not feeling well", "label": "others"},
    {"text": "Can you teach me a new language?", "label": "others"},
    {"text": "What are the latest fashion trends?", "label": "others"},
    {"text": "How do I fix a flat tire?", "label": "others"},
    {"text": "Can you explain the stock market?", "label": "others"},
    {"text": "I feel stressed, what should I do?", "label": "others"},
    {"text": "Can you recommend a workout routine?", "label": "others"},
    {"text": "What are the health benefits of green tea?", "label": "others"},
    {"text": "How do I meditate?", "label": "others"},
    {"text": "Can you explain blockchain?", "label": "others"},
    {"text": "I'm feeling nostalgic, can you play some 90s music?", "label": "others"},
    {"text": "What is the best pet to have?", "label": "others"},
    {"text": "I want to learn photography, where do I start?", "label": "others"},
    {"text": "Can you help me plan a party?", "label": "others"},
    {"text": "I'm looking for a new hobby, any suggestions?", "label": "others"},
    {"text": "I feel hungry", "label": "others"},
    {"text": "I feel lost", "label": "others"},
    {"text": "I feel bored", "label": "others"},
    {"text": "I feel tired", "label": "others"},
    {"text": "I feel confused", "label": "others"},
    {"text": "I feel happy", "label": "others"},
    {"text": "I feel sad", "label": "others"},
    {"text": "I feel excited", "label": "others"},
    {"text": "I feel nervous", "label": "others"},
    {"text": "I feel scared", "label": "others"},
    {"text": "I feel sleepy", "label": "others"},
    {"text": "I feel angry", "label": "others"},
    {"text": "I feel amazed", "label": "others"},
    {"text": "I feel joyful", "label": "others"},
    {"text": "I feel anxious", "label": "others"},
    {"text": "I feel relaxed", "label": "others"},
    {"text": "I feel stressed", "label": "others"},
    {"text": "I feel cheerful", "label": "others"},
    {"text": "I feel gloomy", "label": "others"},
    {"text": "I feel cold", "label": "others"}
]